### ISSUE TITLE
Dijagrami Aktivnosti - Popravke

### ISSUE THREAD

**Issue by ibecir** [amujkic1/OOAD_projekat#2]
0. Rezolucija je zaista slaba i tesko je procitati neke stvari, imate 9 dijagrama a trebate da imate 10 funkcionalnosti. Kao sto smo pricali, za svaku funkcionalnost moramo imati jedan dijagram.

1. "Upravljanje korisnickim racunom" dijagram je prekompleksan i treba ga razbiti bar na 2 dijagrama (Jedan za login a jedan za registraciju). Cilj dijagrama aktivnosti jeste da pokaze protok informacija izmedju razlicitih aktera u sistemu ZA JEDNU FUNKCIONALNOST a ne vise njih u jednom dijagramu. Ovaj dijagram je vrlo tesko pratiti.
2. Dijagram 5: Da li ce zaista Administrator brisati racun ili je to u ovom slucaju sistem jer se racun brise nakon 7 dana? Razmislite o tome
3. Dijagram 7: "Placanje" je los izbor rijeci, mozda da stavite "Obrada transakcije" ili nesto slicno. Takodjer, kad je zavrsena obrada transakcije, korisnik bi trebao da dobije neku potvrdu (email, push notifikaciju odnosno obavjest preko kanala koji koristite za komunikaciju sa korisnicima)

Jos jednom prodjite kroz sve dijagrame, na nekim mjestima mi se cini da imamo previse uslova koji cijelom dijagramu daju jednu dozu konfuzije i nekada je tesko pratiti sam dijagram. Molim Vas da jos jednom pogledate dijagrame koje smo pokrili na vjezbama kao i vise primjera online kako biste dobili bolji osjecaj sta je dijagram aktivnosti i koja mu je svrha. Kad popravite ove stvari, oznacite me na ovaj issue da pogledam i ako bude dobro da mozemo zatvoriti issue.

**Comment by abajric2** [comment]
Dobro večer, ispravile smo greške, pa ako možete da pogledate novu verziju.
@ibecir
